language: c
sudo: required
dist: trusty
install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A3421AFB
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo apt-get -y update
  - sudo apt-get -y install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi gcc xorg-dev libgl1-mesa-dev
script:
  - ./travis-build-firmware.sh

