language: c
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:terry.guo/gcc-arm-embedded'
    packages:
      - gcc-6
      - g++-6
      - cmake
      - xorg-dev
      - libgl1-mesa-dev
      - libfreetype6-dev
      - libglew-dev
      - zlib1g-dev
      - gcc-arm-none-eabi
install:
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  - ./util/bash/glfw-install.sh
  - ./util/bash/glm-install.sh
script:
  - ./util/bash/travis-build.sh

