language: c
sudo: required
dist: trusty
install:
  - sudo apt-get -y update
  - sudo apt-get -y install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi gcc xorg-dev libgl1-mesa-dev
script:
  - scripts/travis-build-firmware.sh

